### ISSUE TITLE
react-native rn 54 supports Blob

### ISSUE THREAD

**Issue by sibelius** [robwalkerco/redux-persist-filesystem-storage#15]
Should we add support to Blob directly from react-native?

and drop `react-native-fetch-blob`?

**Comment by zzorba** [comment]
There also seems to be some indication that `react-native-fetch-blob` has been abandoned, the new react-native contains some warnings and it seems like the maintainers have become unresponsive to PRs. 

Seems like there's a fork that seems to have been updated with some newer dependencies + bug fixes: https://github.com/joltup/rn-fetch-blob

**Comment by robwalkerco** [comment]
I've merged PR #19 which switches to using https://github.com/joltup/rn-fetch-blob and have released to npm as 1.3.0

Thanks for your comments.
