### ISSUE TITLE
Directory creation on redux persist v5

### ISSUE THREAD

**Issue by ganmor** [robwalkerco/redux-persist-filesystem-storage#22]
On first run the file is created when user calls getAllKey.
https://github.com/robwalkerco/redux-persist-filesystem-storage/blob/master/index.js#L63-L66

With redux persist v5, getAllKeys may not be called, for example when calling getstoredstate.
This means that the directory must be created before. 
https://github.com/rt2zz/redux-persist/blob/master/src/getStoredState.js#L7-L38

We could add the test on getItem but that would introduce unneccessary overhead.
A solution could be to make the config method async and create the directory here. Also we could use that change to request the proper android permissions and fallback in case it failed.

We wrapped all that but if you interested I could make a PR.

**Comment by robwalkerco** [comment]
A PR would be great @ganmor.
I guess this would be a breaking change as well, so would need some details to add to a changelog.

**Comment by augusto-altman** [comment]
Hi guys,

I have implemented a solution for this issue on one of my projects. I haven't deployed it to prod yet, but it is already tested. Compared with the solutions proposed here it has the following advantages:

1. It is not a breaking change, it keeps the library signature intact.
2. It does not add unnecessary overhead. It only checks for the directory existence once, either when the library is first loaded (checking the default path) or when the path is changed. In either case, a promise is resolved only once and it is consumed by the rest of the methods afterward.
3. It also validates the existence of the files by key (not only the "root" directory) on `getItem`, but only if an error has happened. This was a problem that I found when I integrated it on my project.

Things to note:

- In my project, we don't use flow. Therefore, the code I am about to share doesn't have flow annotations.
- The code style is adapted to my project's setup.

The code:
`import RNFetchBlob from "rn-fetch-blob";

const defaultStoragePath = `${RNFetchBlob.fs.dirs.DocumentDir}/persistStore`;
const storagePathReadyFactory = path =>
  RNFetchBlob.fs.exists(path).then(exists => {
    return exists
      ? new Promise(resolve => resolve(true))
      : RNFetchBlob.fs.mkdir(path);
  });

let options = {
  storagePath: defaultStoragePath,
  encoding: "utf8",
  toFileName: name => name.split(":").join("-"),
  fromFileName: name => name.split("-").join(":")
};
const pathForKey = key => `${options.storagePath}/${options.toFileName(key)}`;
let storagePathReady = storagePathReadyFactory(defaultStoragePath);

const FilesystemStorage = {
  config: customOptions => {
    if (
      !!customOptions.storagePath &&
      options.storagePath !== customOptions.storagePath
    ) {
      storagePathReady = storagePathReadyFactory(customOptions.storagePath);
    }
    options = {
      ...options,
      ...customOptions
    };
  },
  setItem: (key, value, callback) => {
    return storagePathReady.then(() => {
      return RNFetchBlob.fs
        .writeFile(pathForKey(key), value, options.encoding)
        .then(() => callback && callback())
        .catch(error => callback && callback(error));
    });
  },
  getItem: (key, callback) => {
    return storagePathReady.then(() => {
      const filePath = options.toFileName(key);
      return RNFetchBlob.fs
        .readFile(pathForKey(filePath), options.encoding)
        .then(data => {
          callback && callback(null, data);
          if (!callback) return data;
        })
        .catch(error => {
          return RNFetchBlob.fs
            .exists(filePath)
            .then(exists => {
              if (exists) {
                // The error is not related to the existance of the file
                callback && callback(error);
                if (!callback) throw error;
              }
              return "";
            })
            .catch(() => {
              // We throw the original error
              callback && callback(error);
              if (!callback) throw error;
            });
        });
    });
  },

  removeItem: (key, callback) => {
    return storagePathReady.then(() => {
      return RNFetchBlob.fs
        .unlink(pathForKey(options.toFileName(key)))
        .then(() => callback && callback())
        .catch(error => {
          callback && callback(error);
          if (!callback) throw error;
        });
    });
  },

  getAllKeys: callback => {
    return storagePathReady
      .then(() => {
        return RNFetchBlob.fs
          .ls(options.storagePath)
          .then(files => files.map(file => options.fromFileName(file)))
          .then(files => {
            callback && callback(null, files);
            if (!callback) return files;
          });
      })
      .catch(error => {
        callback && callback(error);
        if (!callback) throw error;
      });
  }
};

FilesystemStorage.clear = callback =>
  FilesystemStorage.getAllKeys((error, keys) => {
    if (error) throw error;

    if (Array.isArray(keys) && keys.length) {
      const removedKeys = [];

      keys.forEach(key => {
        FilesystemStorage.removeItem(key, error => {
          removedKeys.push(key);
          if (error && callback) callback(error, false);
          if (removedKeys.length === keys.length && callback)
            callback(null, true);
        });
      });
      return true;
    }

    callback && callback(null, false);
    return false;
  }).catch(error => {
    callback && callback(error);
    if (!callback) throw error;
  });

export default FilesystemStorage;
`

Please let me know if you see any possible issue I have missed. I would like to have your feedback before deploying it to prod.

Also, if you think it is ok I can create a proper PR.

Best,
Augusto.-

**Comment by robwalkerco** [comment]
Hi Augusto,

Please can you submit this as a PR so that the diff can be viewed easily
and commented upon.

Thanks
