### ISSUE TITLE
Update example migration from AsyncStorage for v5

### ISSUE THREAD

**Issue by hutchy2570** [robwalkerco/redux-persist-filesystem-storage#25]
v5 requires a different approach to migrating from AsyncStorage to FS, see https://github.com/rt2zz/redux-persist/issues/806#issuecomment-425838924

**Comment by robwalkerco** [comment]
Hi @hutchy2570 Thanks for the tip.

I've updated the readme to include a link to the issue comment for V5 users - https://github.com/robwalkerco/redux-persist-filesystem-storage/pull/27
