### ISSUE TITLE
Cannot migrate from AsyncStorage to FS

### ISSUE THREAD

**Issue by Gaia-Nutrition** [robwalkerco/redux-persist-filesystem-storage#28]
I am trying to switch from the standard AsyncStorage adaptor to this FS implementation due to Android filesize limitations.

On iOS when I try to use the suggested method for persisted state migration outlined [here](https://github.com/rt2zz/redux-persist/issues/806#issuecomment-425838924) I am getting the following error:
```
Error: No such file '/Users/ben/Library/Developer/CoreSimulator/Devices/2EA11A5D-A311-4BAB-8AB9-944D5E83791D/data/Containers/Data/Application/B2729C15-11F0-4704-B0BA-3592EA76E4B6/Documents/persistStore/persist-root'
```
This sounds like it's related to #22. Could someone confirm?
Also, is there a fix/workaround yet?

**Comment by robwalkerco** [comment]
@ganmor is this the same issue you reported?
I'm not using redux persist v5, and don't have time at the moment to update to use it, but I'm open to a PR for better support.
