### ISSUE TITLE
Update to Promise based api

### ISSUE THREAD

**Issue by rt2zz** [robwalkerco/redux-persist-filesystem-storage#3]
redux-persist just switched to requiring promise based storage in v5.0.0-beta.13

Unfortunately it is going to be a pain to get everyone updated. Technically the storage can support both (like AsyncStorage and localforage) but since this module is specific to redux-persist may was well just go 100% promises and make the peer dep be redux-persist@5

**Comment by robwalkerco** [comment]
Resolved by #4
