### ISSUE TITLE
Problem on fresh install

### ISSUE THREAD

**Issue by geekazoid-at** [robwalkerco/redux-persist-filesystem-storage#34]
Hi, my app is on the following redux deps:

```    "redux": "^3.7.2",
    "redux-persist": "^4.10.2",
    "redux-persist-filesystem-storage": "1.3.1",
    "redux-saga": "^0.16.0",
```

After upgrading `redux-persist-filesystem-storage` to `1.4.0`, my app won't start properly on a fresh install. I don't know what is happening, but I expect that my startup saga is stuck waiting for `persist/REHYDRATE`.
It is/was hard to debug, but it is reproducible by installing the app, enabling debug mode and installing another version with the updated dep over it.

I think I once saw an error containing `storage.getAllKeys` but I am not sure.

I have no other clues. Thank you for this great lib so far!

**Comment by robwalkerco** [comment]
@geekazoid-at Does v1.3.2 work ok? 
If it does work, can you see anything in https://github.com/robwalkerco/redux-persist-filesystem-storage/pull/33/files that may be breaking it for you?

Perhaps you could try editing the file directly in your node_modules to see if you find a solution.

**Comment by tayyabaAslam** [comment]
@geekazoid-at I too am facing this issue. With following redux dependencies:

> "redux-persist": "^5.10.0",
> "redux-persist-filesystem-storage": "^1.3.1",
>  "redux-saga": "^0.16.0",

**Comment by geekazoid-at** [comment]
I am in vacation and will try that next week when I am back home.

Thank you for your support!

Rob Walker <notifications@github.com> schrieb am Fr., 12. Juli 2019, 09:53:

**Comment by jpsolero** [comment]
I also have this problem, it happens when using redux-persist versions < 5.0.0 on android an ios.

**Comment by psaikali** [comment]
I had it too, I just fixed it doing a new `npm install --save rn-fetch-blob`.

**Comment by robwalkerco** [comment]
Closing this issue, as it looks @psaikali may have found the solution

**Comment by geekazoid-at** [comment]
OK, very late but still I have a conclusion.
Seems like I had a setup problem, as it now runs fine with the following deps on another project:

```
"react-redux": "^6.0.0",
"redux": "^4.0.1",
"redux-persist": "^5.10.0",
"redux-persist-filesystem-storage": "^2.2.0",
```
