### ISSUE TITLE
Does not work on RN < 0.60

### ISSUE THREAD

**Issue by suheb** [robwalkerco/redux-persist-filesystem-storage#35]
The `rn-fetch-blob` package recently release a new version `0.10.16` which includes support for RN `0.60`. But `rn-fetch-blob@0.10.16` is no compatible with previous RN versions (See  [issue](https://github.com/joltup/rn-fetch-blob/issues/403).

This in turn breaks this package for RN versions < 0.60.

Until the `rn-fetch-blob` issue is fixed,  this package should depend on `rn-fetch-blob@0.10.15` as suggested [here](https://github.com/joltup/rn-fetch-blob/issues/403#issuecomment-511827058).

**Comment by darioajr** [comment]
Please, breaking changes need update version not a minor issue, "rn-fetch-blob": "ˆ0.10.15".

**Comment by fiznool** [comment]
Unfortunately this has now broken RN 0.60+ installs, as the podspec for rn-fetch-blob 0.10.15 is not compatible with RN 0.60+.

My suggestion would be to release a major version of this lib which depends on `rn-fetch-blob: ^0.10.16`. This would mean that RN 0.59 and below would use 1.x, and RN 060 and above would use 2.x?

**Comment by robwalkerco** [comment]
Hi @fiznool,
Sounds good to me. 
Would be great to get a suitable PR (including an update to the readme), which would help me get this fixed soonest.

**Comment by fiznool** [comment]
Thanks @robwalkerco - please find at #39

**Comment by robwalkerco** [comment]
#40 had been merged and published as v2.0.0

Thanks @fiznool
