### ISSUE TITLE
App freezes and closes when i save more than 15mb to storage

### ISSUE THREAD

**Issue by azhaubassar** [robwalkerco/redux-persist-filesystem-storage#38]
When I save in storage more than 15mb , my app freezes and after few second closes. I checked it, when i try to save 13mb it's ok. 
Any solutions ?
I use filesystem-storage by changing from `import storage 'redux-persist/lib/storage';
`
to  `import FilesystemStorage from 'redux-persist-filesystem-storage'
`. 
And add to whitelist reducers that i need to store.
**Am I right? And how can i  save large sizes in storage(more than 15mb)**
ANDROID, on iOS it's good

code:
```
import { createStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import { persistStore, persistReducer } from 'redux-persist';
import storage from 'redux-persist/lib/storage';
import { composeWithDevTools } from 'redux-devtools-extension';
import getRootReducer from '@reducers';
import { Platform } from 'react-native';
import FilesystemStorage from 'redux-persist-filesystem-storage'


const persistConfig = {
  key: 'root',
  whitelist: ['pins' ],
  storage: FilesystemStorage,
};

const persistedReducer = persistReducer(persistConfig, getRootReducer());

export default () => {
  const store = createStore(
    persistedReducer,
    composeWithDevTools(applyMiddleware(thunk))
  );
  const persistor = persistStore(store);
  return { store, persistor };
};
```

As you can see I try to save **pins** that more than 15mb to storage...

**Comment by kkushimoto** [comment]
Has there been any progress?

**Comment by azhaubassar** [comment]
> Has there been any progress?

I just wrote my own file system using https://github.com/wkh237/react-native-fetch-blob
I saved data in file like example.json
This is only solution here for me

**Comment by maoapp** [comment]
@azhaubassar Hi, I am facing the same issue , could you share how I can use the react-native-fetch-blob like a storage to get and set json, thanks. :)

**Comment by robwalkerco** [comment]
If you are need to store 15mb of data, its likely that redux/redux-persist is the wrong place to store it.
Perhaps just store the data in a file directly using [react-native-fetch-blob](https://github.com/joltup/rn-fetch-blob) directly
