### ISSUE TITLE
Size of Store

### ISSUE THREAD

**Issue by rahulbhankar786** [robwalkerco/redux-persist-filesystem-storage#43]
Anyone tells me what is the maximum size of this library store.
like AsyncStorage can store 6MB data.
how much data this lib can store?

**Comment by tiagocorreiaitcenter** [comment]
I don't think there's a limit, since its using files to store the data the limit will probably be as much as the device can store. The only downside i can think of is the performance as the files grow

**Comment by robwalkerco** [comment]
Exactly @tiagocorreiaitcenter 
It's just limited by storage size, but as the data stored grows, so will the persist read/write performance. If you are storing data that doesn't really need to be in the persisted state (binary data, images etc...), then you should probably use the file system directly and keep it out of the state.
