### ISSUE TITLE
getAllKeys is not the same as AsyncStorage.getAllKeys

### ISSUE THREAD

**Issue by retyui** [robwalkerco/redux-persist-filesystem-storage#46]
```js
// Where LO is:
global.LO = require('redux-persist-filesystem-storage').default;
```

![image](https://user-images.githubusercontent.com/4661784/82154481-f4de6580-9876-11ea-8d7e-59976f474d46.png)

As you see above I expected that `getAllKeys` returns `[..., 'a:my-super-key']` instead of `[a:my:super:key]`

**Comment by robwalkerco** [comment]
Thanks for reporting the issue.
Please open a PR with a suggested solution.

**Comment by retyui** [comment]
ignore

**Comment by retyui** [comment]
@robwalkerco Thank for good issue solving (sarcasm)
When I write `ignore` I mean that the bot shouldn't close it

**Comment by robwalkerco** [comment]
Ah, understood.

**Comment by robwalkerco** [comment]
@retyui Just looked into this.

The default `toFileName` and `fromFileName` functions at https://github.com/robwalkerco/redux-persist-filesystem-storage/blob/master/index.js#L28-L29 convert `:` to `-` and back again.

If you want to use those characters in your keys, then you may want to provide your own functions like

```js
import FilesystemStorage from 'redux-persist-filesystem-storage'
...

FilesystemStorage.config({
     storagePath: `${RNFetchBlob.fs.dirs.DocumentDir}/persistStore`
});

const persistConfig = {
  key: 'root',
  storage: FilesystemStorage,
  toFileName: (name: string) => name.split(":").join("_"),
  fromFileName: (name: string) => name.split("_").join(":")
}

...
```

**Comment by robwalkerco** [comment]
I have also updated the readme to show all the configurable options and their default values - f21e0e608665a4853d10850e154d265b5bbd1e4d
