### ISSUE TITLE
Crash regarding rn-fetch-blob

### ISSUE THREAD

**Issue by IhorDemedyuk** [robwalkerco/redux-persist-filesystem-storage#48]
![crash](https://user-images.githubusercontent.com/5556051/85722647-2d395500-b6fb-11ea-81b4-ba370ddf26fb.png)

Hi,
Faced this issue after replaced AsyncStorage from '@react-native-community/async-storage' with FilesystemStorage from 'redux-persist-filesystem-storage'

Found that adding custom dependency to rn-fetch-blob v0.12.0  into project fixes the issue. 
Currently redux-persist-filesystem-storage uses rn-fetch-blob v0.10.16
Suppose [library dependency](https://github.com/robwalkerco/redux-persist-filesystem-storage/blob/master/package.json) upgrade will fix this without need to add separate rn-fetch-blob dependency.

**Comment by therealemjy** [comment]
Same issue here, thanks for providing the fix!

**Comment by robwalkerco** [comment]
Thanks for reporting the issue.
Please open a PR with the suggested solution.
