### ISSUE TITLE
unsafe implementation of the HostnameVerifier interface - Google play store warning

### ISSUE THREAD

**Issue by jacky-ew** [robwalkerco/redux-persist-filesystem-storage#52]
Came across 

> unsafe implementation of the HostnameVerifier interface

warning given by google play. 

It seem to be a problem caused by HostnameVerifier on this line of code of `rn-fetch-blob`(dir: rn-fetch-blob > android > src > main > java > com > RNFetchBlob > RnFetchBlobUtils.java):

```
            OkHttpClient.Builder builder = client.newBuilder();
            builder.sslSocketFactory(sslSocketFactory, x509TrustManager);
            builder.hostnameVerifier(new HostnameVerifier() {
                @Override
                public boolean verify(String hostname, SSLSession session) {
                    return true;
                }
            });
```

on this article (https://www.programmersought.com/article/41342996449/), it proposed to handle it like so. But on our case we dont really have any handling of HTTPS need to be done hence will just modify this block to `return false`.

My question is will it affect the functionality of this library?

**Comment by robwalkerco** [comment]
This library does not make use of any of the http features of `rn-fetch-blob`. It just uses the filesystem functions, so I don't think it will affect any functionality here.
