### ISSUE TITLE
Possible that rn-fetch-blob will go unmaintained

### ISSUE THREAD

**Issue by davidpaulhunt** [robwalkerco/redux-persist-filesystem-storage#53]
According to [this issue](https://github.com/joltup/rn-fetch-blob/issues/666), `rn-fetch-blob` may go unmaintained.

Is this something we should worry about? If so, how can we help to ensure this project doesn't suffer? How can we (or I) help?

Feel free to close this if you are aware or already have a plan.

Cheers.

**Comment by robwalkerco** [comment]
There are several other similar projects that use different storage options. Perhaps [redux-persist-fs-storage](https://github.com/leethree/redux-persist-fs-storage) may be better to use long-term?
There are others listed on the [redux-persist readme](https://github.com/rt2zz/redux-persist#storage-engines)

It should be possible to move data from one system to another without effecting users. You will need to load data from one redux-persist config, and use that to hydrate another.

Perhaps I should add a notice to the readme regarding

**Comment by davidpaulhunt** [comment]
@robwalkerco Cool, appreciate the feedback!
