### ISSUE TITLE
Update rn-fetch-blob dependency.

### ISSUE THREAD

**Issue by cristianoccazinsp** [robwalkerco/redux-persist-filesystem-storage#55]
rn-fetch-blob was deprecated/unmaintained once again (https://github.com/joltup/rn-fetch-blob/issues/666)

The new home for this library (new fork) is at https://github.com/RonRadtke/react-native-blob-util

Would you consider either removing the hard dependency to rn-fetch-blob so either can be used, or just migrating to the new dependency? Otherwise, users using this library will be forever stuck with the deprecated one.

Thanks.

**Comment by imranMnts** [comment]
@robwalkerco Do we have any update on this request please?

Currently `rn-fetch-blob` is using deprecated android permission which will be rejected by Google in future.

**Comment by robwalkerco** [comment]
Thanks for pointing out the new fork.

Just took a quick look at it.

I'm happy switch to the new fork once its stable, but probably best to wait for this to be fixed first? https://github.com/RonRadtke/react-native-blob-util/pull/27

**Comment by imranMnts** [comment]
@robwalkerco 

Issue mentioned looks like fixed in v0.13.7

https://github.com/RonRadtke/react-native-blob-util/pull/27#issuecomment-833312896
