### ISSUE TITLE
Migrating AsyncStorage to Redux-Persist-Filesystem-Storage

### ISSUE THREAD

**Issue by JonnyLinja** [robwalkerco/redux-persist-filesystem-storage#7]
I have an existing app in production with the Android storage issue. I want to migrate to Redux-Persist-Filesystem-Storage without losing the previous store. How would I go about this?

Would it be possible to look through the keys of AsyncStorage and duplicate what I can? I am on V4 of redux-persist, so supposedly there is https://github.com/rt2zz/redux-persist/blob/master/src/integration/getStoredStateMigrateV4.js

**Comment by sospedra** [comment]
I'm running in the same problem. Specially for mantaining the user logged in and the current route.
We cannot swap to this (btw awesome) project if migrations are not possible 😞

**Comment by maxkomarychev** [comment]
I've got similar issue. [This is how I tackled it](https://github.com/rt2zz/redux-persist/issues/679) (note there are couple questions I'm asking, so I am still not 100% sure this is the right way).

 It is supposed to safely fallback to previous data in `AsyncStorage` if there is nothing stored before in fs storage.

I'd appreciate if you can check it out and share your opinion if it works for you or no, thanks!

**Comment by maxkomarychev** [comment]
As far as I understand the migration mentioned above is to migrate *state shape* between v4 and v5 and doesn't work if you want to hot-replace the storage engine itself.

**Comment by robwalkerco** [comment]
I haven’t tried migrating between different storage engine myself, but am keen to hear what works for you, as I think I will need to do this myself soon an a project.

**Comment by robwalkerco** [comment]
@maxkomarychev Just tried your solution at rt2zz/redux-persist#679 and it worked great 👏 

I'm going to close this task, as it seems there is a working solution now.
